# !!! This file is managed by lhsystems/base-sync sync-*.yml workflow and periodically synced !!!
name: "terraform-docs"

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  terraform-docs:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN_GITHUB }} # as per https://github.com/peter-evans/create-pull-request/issues/48#issuecomment-536204092
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          working-dir: .
          output-file: README.md
          output-method: replace
          git-push: "true"
          git-push-user-name: "lhsystems-automation"
          git-push-user-email: "techcoe.mailbox@lhsystems.com"
          config-file: .github/terraform-docs.yml
