# !!! This file is managed by lhsystems/base-sync sync-*.yml workflow and periodically synced !!!
name: "terraform-quality"

on:
  push:
    branches:
      - '!master'
    paths-ignore:
      - '.github/**'
  pull_request:
    types: [opened, synchronize, reopened, edited] # edited because of tf-docs: https://stackoverflow.com/questions/65093647/in-github-actions-how-can-i-trigger-on-push-but-only-if-a-pr-is-active
    paths-ignore:
      - '.github/**'
      - '.devcontainer/**'
      - '.vscode/**'

env:
  TERRAFORM_CLOUD_TOKENS: |
    app.terraform.io=${{ secrets.TF_API_TOKEN }}

jobs:
  terraform-quality:
    runs-on: [self-hosted, linux] # to use github-runners use "ubuntu-latest" instead
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Evaluate Terraform version
        id: terraform-version
        uses: dflook/terraform-version@v1
        with:
          path: .

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.terraform-version.outputs.terraform }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Setup terraform lint (tflint)
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Init (init)
        id: init
        run: terraform init -upgrade

      - name: Terraform Format (fmt)
        id: fmt
        run: terraform fmt --check --diff

      - name: Terraform tflint (tflint)
        id: tflint
        shell: bash
        run: |
          TFLINT_LOG=info tflint --module -f compact

      - name: Terraform Security (tfsec)
        id: tfsec
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.github_token }}
          working_directory: "."
          reporter: github-pr-review
          fail_on_error: "true" # Fail action if errors are found
          filter_mode: "added"
          flags: "" # Optional

      - name: Terraform Validate (validate)
        id: validate
        uses: dflook/terraform-validate@v1
        with:
          path: .
